name: flutter_app
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  #google map
  flutter_google_places: ^0.2.4
  google_maps_flutter: ^1.0.3

  #Internet Check
  connectivity: ^2.0.2

  #Permission handler
  permission_handler: ^5.0.1+1
  audioplayers: ^0.17.4
#  location_permissions: ^3.0.0
  #Responsive Flutter
  responsive_flutter: ^0.0.4

  #Flutter toast
  fluttertoast: ^7.1.6

  #location
  geolocator: ^5.3.1
#  location: ^3.2.1
  background_location: ^0.3.0

  #shared Preference
  shared_preferences: ^0.5.12+4

  #Path provider
  path_provider: ^1.2.0
#  webview_flutter: ^1.0.7

  #double tap to close
  double_back_to_close_app: ^1.2.0
  url_launcher: ^5.7.10
  #Dialog
  progress_dialog: ^1.2.4
  flutter_easyloading: ^2.0.0


  #  Bloc
#  flutter_bloc: ^3.0.0
#  equatable: ^1.0.0
#  rxdart: ^0.23.1

  #Api calling
  http: ^0.12.0
  meta: ^1.1.6
#  dio: ^3.0.8

  #Image picker
  image_picker: ^0.6.7+17


  #Agora
  agora_rtc_engine: ^3.2.1
  uuid: ^2.0.2
#  bringtoforeground: ^0.0.2
#  get_it: ^5.0.6
  flutter_ios_voip_kit: ^0.0.5
#  flutter_apns: ^1.4.3
  geocoder: ^0.2.1
#  flutter_voip_push_notification: ^0.0.3
#  flutter_call_kit: ^0.0.2
#  system_alert_window: ^0.4.2+2
#  workmanager: ^0.2.3
  #Local Notification
#  android_intent: ^0.3.7+7
#  get_it: ^5.0.6
  flutter_local_notifications: ^3.0.2
#  awesome_notifications: ^0.0.5+5
  callkeep: ^0.2.3+1
#  flutter_callkeep: ^0.1.8
#  is_lock_screen: ^1.0.0
  #Firebase
  firebase_core: 0.5.3
  firebase_database: ^4.2.0
  firebase_analytics: ^6.1.0
  firebase_storage: ^5.0.1
  firebase_auth: ^0.18.2
  firebase_messaging: ^7.0.3
  cloud_firestore: ^0.14.2
#  flutter_callkeep: ^0.1.8
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  crypto: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.0.0
  json_serializable: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/images/arrow_right_ic.png
    - assets/images/back_ic.png
    - assets/images/become_a_mediator_ic.png
    - assets/images/chat_ic.png
    - assets/images/get_helap_ic.png
    - assets/images/gps_ic.png
    - assets/images/location_pin_ic.png
    - assets/images/mediator_pin.png
    - assets/images/phone_call_ic.png
    - assets/images/profile_pic_placeholder.png
    - assets/images/radio_btn.png
    - assets/images/radio_selected_btn.png
    - assets/images/send_ic.png
    - assets/images/send_graphic_ic.png
    - assets/images/shake_hand_logo.png
    - assets/images/user_pin.png
    - assets/images/pending_ic.png
    - assets/images/philly_truce_text_logo.png
    - assets/images/map_ic.png
    - assets/images/map_ic1.png
    - assets/images/right_arrow_ic.png
    - assets/images/not_request_graphic.png
    - assets/images/profile_ic.png
    - assets/images/group.png
    - assets/images/group_reject.png
    - assets/images/send_mail_ic.png

    - assets/ringtone.mp3
    - assets/phone_ring.mp3
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  fonts:
    - family: Oswald
      fonts:
        - asset: font/Oswald-Bold.ttf
        - asset: font/Oswald-Medium.ttf
        - asset: font/Oswald-SemiBold.ttf
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
